### ISSUE TITLE
Problem about float type

### ISSUE THREAD

**Issue by LambdaEd1th** [oobol2000oo/RETON#7]
'Infinity', '-Infinity' and 'NaN' are existed in the float and double type.
![PositiveInfinity](https://user-images.githubusercontent.com/14805065/65694011-c45b7880-e0a7-11e9-8ad9-251ea3d4d61f.jpg)
![NegativeInfinity](https://user-images.githubusercontent.com/14805065/65694304-3c29a300-e0a8-11e9-89c6-ec13449fa981.jpg)

When converting these values, the tool will convert them into null without distinction. Here is the sample file.
[PlantLevels.zip](https://github.com/h3x4n1um/RETON/files/3658167/PlantLevels.zip)

**Comment by h3x4n1um** [comment]
Thankyou for pointing out, I'm gonna look into this special case

**Comment by h3x4n1um** [comment]
This problem can be fixed by using ~~[`std::numeric_limits`](https://en.cppreference.com/w/cpp/types/numeric_limits)~~ [std::isnan](https://en.cppreference.com/w/cpp/numeric/math/isnan) and [std::isinf](https://en.cppreference.com/w/cpp/numeric/math/isinf)

My problem is when converting json2rton, if it reads a `Infinity`, `-Infinity` or `NaN`, should it processes as `string` or `floating-point` type? And if it processes as `floating-point` what if someone writes in json like this:

```json
{"Infinity": "NaN"}
```

**Comment by nineteendo** [comment]
If someone writes "Infinity": "NaN" in json this should definitely be treated as a string, no need to detect that.

Thanks for pointing this out, luckily in python with the json library allow_nan is set to True by default, so this doesn't cause issues in my python alternative to RETON.
