### ISSUE TITLE
The key type 0x52 cannot read

### ISSUE THREAD

**Issue by hufex** [oobol2000oo/RETON#9]
Hello . 

when trying to convert a file it throws me the following error:

```
rton-json made by H3x4n1um
Version: 2.7.7 - 32-bit executable
Compiled on Oct 24 2019 at 23:08:16
Credits: nlohmann for his awesome JSON parser and fifo_map

Enter file or folder path: /dos/Descargas/PvZ2TodoGratis(7.2.1)JhalebNOPE/products-20200310.rton

Processing file "/dos/Descargas/PvZ2TodoGratis(7.2.1)JhalebNOPE/products-20200310.rton" - RTON Detected
Error reading bytecode 0x52 at 0x8000!!!
Error code: 2

Finished

```
Files:
https://drive.google.com/drive/folders/1zE3Zs3UNPLi7xqR5-hJFNpLAjOzW5AeQ?usp=sharing

Any suggestions.

**Comment by h3x4n1um** [comment]
I'll take a look into it

**Comment by h3x4n1um** [comment]
Your file is corrupted

**Comment by nineteendo** [comment]
It seems like suddenly your file restarts, if you interpret that as a new file this is the output:
[products-20200310.zip](https://github.com/h3x4n1um/RETON/files/6610760/products-20200310.zip)
It think your desired output is section2.json, since it's just a longer version of section1.json

This might be still be interesting to support though, you could use it to split up a section file created by OBBPatcher into multiple subsections. Allowing you to edit them as json.
